export declare const AUTH_PIN_LENGTH = 4;
export declare const AUTH_PIN_REGEX: RegExp;
export declare const AUTH_MAX_ATTEMPTS = 3;
export declare const AUTH_LOCKOUT_DURATION_MS: number;
export declare const QR_TOKEN_EXPIRATION_MS: number;
export declare const QR_TOKEN_REFRESH_INTERVAL_MS: number;
export declare const LOCATION_VALIDATION_RADIUS_M = 50;
export declare const LOCATION_VALIDATION_ACCURACY_THRESHOLD_M = 30;
export declare const LOCATION_JUMP_THRESHOLD_M = 1000;
export declare const LOCATION_JUMP_TIME_THRESHOLD_MS: number;
export declare const RAPID_SCAN_THRESHOLD_MS: number;
export declare const DEVICE_SWITCH_THRESHOLD_MS: number;
export declare const DEFAULT_PAGE_SIZE = 20;
export declare const MAX_PAGE_SIZE = 100;
export declare const MAX_IMPORT_BATCH_SIZE = 1000;
export declare const ALLOWED_IMPORT_FORMATS: string[];
export declare const ATTENDANCE_STATUSES: readonly ["present", "absent", "late", "early_leave"];
export declare const DETECTION_STATUSES: readonly ["normal", "suspicious", "blocked"];
export declare const ERROR_INVALID_PIN = "Invalid PIN";
export declare const ERROR_PIN_ATTEMPTS_EXCEEDED = "Too many PIN attempts. Please try again later.";
export declare const ERROR_DEVICE_NOT_BOUND = "Device not bound. Please bind your device first.";
export declare const ERROR_LOCATION_OUT_OF_RANGE = "Location out of valid range.";
export declare const ERROR_UNAUTHORIZED = "Unauthorized access.";
export declare const ERROR_NOT_FOUND = "Resource not found.";
export declare const ERROR_INVALID_REQUEST = "Invalid request.";
export declare const ERROR_INTERNAL_SERVER = "Internal server error.";
export declare const SUCCESS_LOGIN = "Login successful";
export declare const SUCCESS_ATTENDANCE_RECORDED = "Attendance recorded successfully";
export declare const SUCCESS_DEVICE_BOUND = "Device bound successfully";
export declare const SUCCESS_IMPORT_COMPLETED = "Import completed successfully";
export declare const NRP_LENGTH = 8;
export declare const NRP_REGEX: RegExp;
export declare const WS_EVENT_STATS_UPDATE = "stats:update";
export declare const WS_EVENT_ACTIVITY_LOG = "activity:log";
export declare const WS_EVENT_ALERT = "alert";
export declare const WS_EVENT_QR_REFRESH = "qr:refresh";
//# sourceMappingURL=index.d.ts.map